version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: setlist
      POSTGRES_PASSWORD: setlist
      POSTGRES_DB: setlist
    ports: ["5432:5432"]
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: setlist
      RABBITMQ_DEFAULT_PASS: setlist
    ports: ["5672:5672", "15672:15672"]
  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports: ["6333:6333"]

